---
- name: Ensure auditd is installed
  package:
    name: '{{ role_auditd_packages }}'
    state: present

- name: Deploy auditd configuration from template
  template:
    src: '{{ role_auditd_conf_file.src }}'
    dest: '{{ role_auditd_conf_file.dest }}'
    backup: '{{ role_auditd_conf_file.backup | default(omit) }}'
    attributes: '{{ role_auditd_conf_file.attributes | default(omit) }}'
    owner: '{{ role_auditd_conf_file.owner | default("root") }}'
    group: '{{ role_auditd_conf_file.group | default("root") }}'
    mode: '{{ role_auditd_conf_file.mode | default("0640") }}'
    block_start_string: '{{ role_auditd_conf_file.block_start_string | default(omit) }}'
    block_end_string: '{{ role_auditd_conf_file.block_end_string | default(omit) }}'
    variable_start_string: '{{ role_auditd_conf_file.variable_start_string | default(omit) }}'
    variable_end_string: '{{ role_auditd_conf_file.variable_end_string | default(omit) }}'
    lstrip_blocks: '{{ role_auditd_conf_file.lstrip_blocks | default(omit) }}'
    trim_blocks: '{{ role_auditd_conf_file.trim_blocks | default(omit) }}'
    newline_sequence: '{{ role_auditd_conf_file.newline_sequence | default(omit) }}'
    output_encoding: '{{ role_auditd_conf_file.output_encoding | default(omit) }}'
    selevel: '{{ role_auditd_conf_file.selevel | default(omit) }}'
    serole: '{{ role_auditd_conf_file.serole | default(omit) }}'
    setype: '{{ role_auditd_conf_file.setype | default(omit) }}'
    seuser: '{{ role_auditd_conf_file.seuser | default(omit) }}'
    unsafe_writes: '{{ role_auditd_conf_file.unsafe_writes | default(omit) }}'
    follow: '{{ role_auditd_conf_file.follow | default(omit) }}'
    force: '{{ role_auditd_conf_file.force | default(omit) }}'
    validate: '{{ role_auditd_conf_file.validate | default(omit) }}'
  when:
    - role_auditd_conf_file is defined

- name: Deploy auditd rules
  block:
    - name: Populate auditd rules as file lists
      set_fact:
        role_auditd_rules_file_list: '{{ role_auditd_rules_file_list | default([]) + vars[item] }}'
      loop: "{{ vars.keys() | select('match', '^role_auditd_rules_file_list.*$') | list }}"

    - name: Deploy auditd rules as file files from template
      template:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        backup: '{{ item.backup | default(omit) }}'
        attributes: '{{ item.attributes | default(omit) }}'
        owner: '{{ item.owner | default("root") }}'
        group: '{{ item.group | default("root") }}'
        mode: '{{ item.mode | default("0640") }}'
        block_start_string: '{{ item.block_start_string | default(omit) }}'
        block_end_string: '{{ item.block_end_string | default(omit) }}'
        variable_start_string: '{{ item.variable_start_string | default(omit) }}'
        variable_end_string: '{{ item.variable_end_string | default(omit) }}'
        lstrip_blocks: '{{ item.lstrip_blocks | default(omit) }}'
        trim_blocks: '{{ item.trim_blocks | default(omit) }}'
        newline_sequence: '{{ item.newline_sequence | default(omit) }}'
        output_encoding: '{{ item.output_encoding | default(omit) }}'
        selevel: '{{ item.selevel | default(omit) }}'
        serole: '{{ item.serole | default(omit) }}'
        setype: '{{ item.setype | default(omit) }}'
        seuser: '{{ item.seuser | default(omit) }}'
        unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'
        follow: '{{ item.follow | default(omit) }}'
        force: '{{ item.force | default(omit) }}'
        validate: '{{ item.validate | default(omit) }}'
      loop: '{{ role_auditd_rules_file_list }}'
      when:
        - item.state == 'present'
  always:
    - name: Cleanup unwanted configuration files
      file:
        path: '{{ item.dest }}'
        state: absent
      loop: '{{ role_auditd_rules_file_list }}'
      when:
        - item.state == 'absent'

### Auditd service can only be restarted/reloaded during boot
- name: Ensure auditd is enabled
  service:
    name: auditd
    enabled: True

...
